# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dolt_pb2 as dolt__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug.proto',
  package='dOLT',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x64\x65\x62ug.proto\x12\x04\x64OLT\x1a\ndolt.proto2\x9e\x01\n\x05\x44\x65\x62ug\x12!\n\x05Start\x12\x0b.dOLT.Empty\x1a\x0b.dOLT.Empty\x12 \n\x04Stop\x12\x0b.dOLT.Empty\x1a\x0b.dOLT.Empty\x12%\n\x07SendCmd\x12\r.dOLT.OmciMsg\x1a\x0b.dOLT.Empty\x12)\n\tRecvReply\x12\x0b.dOLT.Empty\x1a\r.dOLT.OmciMsg0\x01\x62\x06proto3')
  ,
  dependencies=[dolt__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DEBUG = _descriptor.ServiceDescriptor(
  name='Debug',
  full_name='dOLT.Debug',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=34,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='dOLT.Debug.Start',
    index=0,
    containing_service=None,
    input_type=dolt__pb2._EMPTY,
    output_type=dolt__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='dOLT.Debug.Stop',
    index=1,
    containing_service=None,
    input_type=dolt__pb2._EMPTY,
    output_type=dolt__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendCmd',
    full_name='dOLT.Debug.SendCmd',
    index=2,
    containing_service=None,
    input_type=dolt__pb2._OMCIMSG,
    output_type=dolt__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RecvReply',
    full_name='dOLT.Debug.RecvReply',
    index=3,
    containing_service=None,
    input_type=dolt__pb2._EMPTY,
    output_type=dolt__pb2._OMCIMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEBUG)

DESCRIPTOR.services_by_name['Debug'] = _DEBUG

# @@protoc_insertion_point(module_scope)
