# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dolt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dolt.proto',
  package='dOLT',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndolt.proto\x12\x04\x64OLT\"\x07\n\x05\x45mpty\"X\n\x07OmciMsg\x12\x0e\n\x06olt_id\x18\x01 \x01(\t\x12\x0f\n\x07slot_id\x18\x02 \x01(\x07\x12\x0f\n\x07intf_id\x18\x03 \x01(\x07\x12\x0e\n\x06onu_id\x18\x04 \x01(\x07\x12\x0b\n\x03pkt\x18\x05 \x01(\x0c\x32]\n\x04\x64OLT\x12(\n\x08SendOmci\x12\r.dOLT.OmciMsg\x1a\x0b.dOLT.Empty(\x01\x12+\n\x0bReceiveOmci\x12\x0b.dOLT.Empty\x1a\r.dOLT.OmciMsg0\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='dOLT.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_OMCIMSG = _descriptor.Descriptor(
  name='OmciMsg',
  full_name='dOLT.OmciMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='olt_id', full_name='dOLT.OmciMsg.olt_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot_id', full_name='dOLT.OmciMsg.slot_id', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intf_id', full_name='dOLT.OmciMsg.intf_id', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='onu_id', full_name='dOLT.OmciMsg.onu_id', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pkt', full_name='dOLT.OmciMsg.pkt', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['OmciMsg'] = _OMCIMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'dolt_pb2'
  # @@protoc_insertion_point(class_scope:dOLT.Empty)
  ))
_sym_db.RegisterMessage(Empty)

OmciMsg = _reflection.GeneratedProtocolMessageType('OmciMsg', (_message.Message,), dict(
  DESCRIPTOR = _OMCIMSG,
  __module__ = 'dolt_pb2'
  # @@protoc_insertion_point(class_scope:dOLT.OmciMsg)
  ))
_sym_db.RegisterMessage(OmciMsg)



_DOLT = _descriptor.ServiceDescriptor(
  name='dOLT',
  full_name='dOLT.dOLT',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=212,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendOmci',
    full_name='dOLT.dOLT.SendOmci',
    index=0,
    containing_service=None,
    input_type=_OMCIMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveOmci',
    full_name='dOLT.dOLT.ReceiveOmci',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_OMCIMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOLT)

DESCRIPTOR.services_by_name['dOLT'] = _DOLT

# @@protoc_insertion_point(module_scope)
